// web/src/components/Consultation.jsx
import { useState } from 'react';
import axios from 'axios';
import Section from './Section';
const Consultation = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    date: '',
    time: '',
    comments: '',
  });
  
  const [message, setMessage] = useState('');

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://localhost:2301/api/appointments/', formData);
      setMessage(`Appointment created successfully!Note Down your Tracking Id to check the status of your appointment  Tracking ID: ${response.data.trackingId}`);
    } catch (error) {
      console.error(error); 
      setMessage('Error creating appointment');
    }
  };

  return (
    <Section id="Consult">
    <div className="max-w-lg mx-auto p-6 bg-white shadow-md rounded-lg mt-10">
      <h2 className="text-2xl font-semibold text-center text-gray-800 mb-6">BOOK YOUR APPOINTMENT</h2>
      <form onSubmit={handleSubmit} className="space-y-4">
        <input
          type="text"
          name="name"
          placeholder="Name"
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <input
          type="email"
          name="email"
          placeholder="Email"
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <input
          type="date"
          name="date"
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <input
          type="time"
          name="time"
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <textarea
          name="comments"
          placeholder="Reason for Appointment"
          onChange={handleChange}
          required
          className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none h-24"
        ></textarea>
        <button
          type="submit"
          className="w-full bg-blue-500 text-white font-semibold py-2 rounded-md hover:bg-blue-600 transition-colors"
        >
          Submit
        </button>
      </form>
      {message && (
        <p className="text-center text-green-600 font-medium mt-4">
          {message}
        </p>
      )}
    </div>
    </Section>
  );
};

export default Consultation;

// admin/src/app/consultation/consultation.component.ts
import { Component, OnInit } from '@angular/core';
import { ConsultationService } from '../consultation.service';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-consultation',
  templateUrl: './consultation.component.html',
  styleUrls: ['./consultation.component.css']
})
export class ConsultationComponent implements OnInit {
  consultations: any[] = [];
  statusOptions = ['pending', 'confirmed', 'canceled'];
  message = '';

  constructor(private consultationService: ConsultationService) {}

  ngOnInit(): void {
    this.getConsultations();
  }

  getConsultations(): void {
    this.consultationService.getAllConsultations().subscribe(
      (data) => this.consultations = data,
      (error) => console.error('Error fetching consultations:', error)
    );
  }

  updateStatus(id: string, newStatus: string): void {
    this.consultationService.updateStatus(id, newStatus).subscribe(
      () => {
        this.consultations = this.consultations.map(consultation =>
          consultation._id === id ? { ...consultation, status: newStatus } : consultation
        );
        Swal.fire({
          text:'success',
          icon:'success'
        })
      },
      (error) => {
        console.error('Error updating status', error);
      }
    );
  }
}

<div class="overflow-x-auto">
  <table class="table-auto w-full text-center border border-gray-300 rounded-lg shadow-md mt-6">
    <thead class="bg-blue-100 text-blue-900 uppercase font-semibold">
      <tr>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Name</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Email</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Date</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Time</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Status</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Update Status</th>
        <th class="px-4 py-3 border-b border-gray-300 whitespace-nowrap">Action</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let consultation of consultations" class="hover:bg-gray-50">
        <td class="border px-4 py-3 whitespace-nowrap">{{ consultation.name }}</td>
        <td class="border px-4 py-3 whitespace-nowrap">{{ consultation.email }}</td>
        <td class="border px-4 py-3 whitespace-nowrap">{{ consultation.date | date }}</td>
        <td class="border px-4 py-3 whitespace-nowrap">{{ consultation.time }}</td>
        <td class="border px-4 py-3 whitespace-nowrap">{{ consultation.status }}</td>
        <td class="border px-4 py-3">
          <select
            [(ngModel)]="consultation.status"
            class="px-3 py-1 border border-gray-300 rounded focus:outline-none focus:ring focus:border-blue-300"
          >
            <option *ngFor="let option of statusOptions" [value]="option">
              {{ option }}
            </option>
          </select>
        </td>
        <td class="border px-4 py-3">
          <button
            (click)="updateStatus(consultation._id, consultation.status)"
            class="px-4 py-2 bg-blue-500 text-white font-semibold rounded hover:bg-blue-600 transition-colors"
          >
            Update
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
